version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: juan.aranda.galvis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345